### ISSUE TITLE
Add link extractor to plantuml parser

### ISSUE THREAD

**Issue by b0g3r** [b0g3r/plantuml2freemind#16]

**Comment by etolstoy** [comment]
А про какие ссылки ты тут говоришь? Можешь примеров накидать?

**Comment by b0g3r** [comment]
```plantuml
@startmindmap
* Teamlead Roadmap
left side
** Personal Skills
***_ Отношения
****_ Эмпатия
****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/self-improvement/emotional-intelligence.md Эмоциональный интеллект]]
****_ Понимание ценности различий
@endmindmap
```

![image](https://user-images.githubusercontent.com/19777948/68111529-5e60dd00-ff00-11e9-8950-a1ef08d38104.png)

**Comment by etolstoy** [comment]
Давай запилю сегодня.

**Comment by etolstoy** [comment]
Только кажется лучше относительные ссылки, а не абсолютные, чтобы форки работали.

**Comment by b0g3r** [comment]
Надо проверить как они будут работать 🤔 Парсер в любом случае не должен отличаться

**Comment by b0g3r** [comment]
Closed by #23
