### ISSUE TITLE
Add data-structure for nodes instead of dicts

### ISSUE THREAD

**Issue by b0g3r** [b0g3r/plantuml2freemind#19]
We use awful non-typed dicts for storing nodes data:
https://github.com/b0g3r/plantuml2freemind/blob/29f360584700eaa00af670fb6e88ac99534bdacb/plantuml2freemind/parsers/plantuml.py#L51-L58

A good candidate for replacement is [attrs](https://www.attrs.org/en/stable/). You need to create a few custom types for parser-node (with `level`), for root-node (with `right` and `left` branch), and for child-node (without `level` and with recursive `children`).

**Comment by ave2me** [comment]
I'll take this one.
